// import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=""
    >
      <body className="min-h-full flex flex-col">
        {children}
       <Toaster
        position="top-right"
        richColors
        expand={true}
        duration={2000}
        // closeButton={false}
        visibleToasts={3}
        toastOptions={{
          style: {
            maxWidth: "90vw",
          },
        }}
      />
      </body>
    </html>
  );
}
